import { Rule, rules } from "./rules";

export let defaultErrors: { [key in keyof typeof rules] } = {
    required: '%s不能为空',
    // matches: '%s与%s不匹配',
    // "default": 'The %s field is still set to default, please change.',
    // equal: '%s和%s必须相同',
    // email: '不是有效的邮箱地址',
    // valid_emails: 'The %s field must contain all valid email addresses.',
    // minLength: '%s至少包含%s个字符',
    // maxLength: '%s不能超过%s字符',
    // exact_length: 'The %s field must be exactly %s characters in length.',
    // greater_than: 'The %s field must contain a number greater than %s.',
    // less_than: 'The %s field must contain a number less than %s.',
    // alpha: 'The %s field must only contain alphabetical characters.',
    // alpha_numeric: 'The %s field must only contain alpha-numeric characters.',
    // alpha_dash: 'The %s field must only contain alpha-numeric characters, underscores, and dashes.',
    // numeric: '请数入数字',
    // integer: 'The %s field must contain an integer.',
    // decimal: 'The %s field must contain a decimal number.',
    // is_natural: 'The %s field must contain only positive numbers.',
    // is_natural_no_zero: 'The %s field must contain a number greater than zero.',
    // ip: 'The %s field must contain a valid IP.',
    // valid_base64: 'The %s field must contain a base64 string.',
    // valid_credit_card: 'The %s field must contain a valid credit card number.',
    // is_file_type: 'The %s field must contain only %s files.',
    // valid_url: 'The %s field must contain a valid URL.',
    // greater_than_date: 'The %s field must contain a more recent date than %s.',
    // less_than_date: 'The %s field must contain an older date than %s.',
    // greater_than_or_equal_date: 'The %s field must contain a date that\'s at least as recent as %s.',
    // less_than_or_equal_date: 'The %s field must contain a date that\'s %s or older.',
    mobile: '请输入正确的手机号码',
    // custom: '请输入正确制',
}